routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('frontend.index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

//	Custom routes
	Route::resource('sales_people', 'SalePersonController');


	Route::resource('managers', 'ManagerController');
	Route::resource('pos', 'PosController');

	Route::post('possearch', 'PosController@search')->name('Search');

	Route::resource('townships', 'TownshipController');
    Route::resource('categories', 'CategoryController');
    Route::resource('item', 'ItemController');
    Route::resource('shop','ShopController');

    Route::post('sale', 'SaleController@store')->name('sale');
});


Route::middleware(['role:Sales'])->group(function () {

});

Route::middleware(['role:Manager'])->group(function () {

});

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Item extends Model
{
	use SoftDeletes;

    protected $fillable=['item_code','name','initial_price','sale_price','quantity'];

    protected $dates = ['deleted_at'];

    public function category()
     {
     	return $this->belongsTo('App\Category');
     }

}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Item;
use App\Category;
use App\Shop;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ItemController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:Manager');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::where('user_id','=',Auth::id())->get();
        return view ('item.index', compact('items'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = DB::table('categories')
                    ->where('user_id','=',Auth::id())
                    ->select('*')
                     ->get();

        return view('item.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

//        $request->validate([
//            "user_id"=>"required",
//           "category_id" => "required",
//            "name" => "required ",
//            "initial_price" => "required",
//            "sale_price" => "required",
//            "quantity" => "required"
//        ]);


        $item=New Item;
        $item ->user_id = Auth::id();
        $item->category_id = request('category_id');
        $category = Category::find(request('category_id'));
        $category_code = $category->code_no;
        if (count(Item::all())>0 && Item::orderBy('id', 'desc')->first()->category_id == $category->id){
            $item->item_code =++Item::orderBy('id', 'desc')->first()->item_code;
        }else {
            $item-> item_code = $category_code . '000';
        }
        $item->name = request('name');
        $item->initial_price = request('initial_price');
        $item->sale_price = request('sale_price');
        $item->quantity = request('quantity');
        $item->save();
        return redirect()->route('item.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = DB::table('categories')
                    ->where('user_id','=',Auth::id())
                    ->select('*')
                     ->get();
        $item = Item::find($id);
        return view('item.edit', compact('item','category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


        $item = Item::find($id);

        // $item -> user_id = request('user_id');
        $item-> category_id=request('category_id');
        $item-> item_code=request('item_code');
        $item-> name=request('name');
        // $item-> initial_price=request('initial_price');
        $item-> sale_price=request('sale_price');
        $item-> quantity=request('quantity');

        $item->save();


         return redirect()->route('item.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Item::find($id);
        $item -> delete();

        return redirect()->route('item.index');
    }
}

resources/views/item/create.blade.php
@extends('layouts.app')

@section('content')
    {{-- Header Background--}}
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-7">
    </div>
    <div class="card shadow mb-4 ml-5 mr-5 mt--7">
        <div class="card-header">
            <h2>Create Items</h2>
        </div>
        <form method="POST" action="{{route('item.store')}}">
          <div class="container">
        	@csrf

  <div class="form-group row">
          <div class="col-sm-12">

            <label for="category_id" class="col-form-label d-inline-block">Category</label>
            <select class="form-control" name="category_id">

              @foreach ($category as $row)
                <option value="{{$row->id}}">{{$row->name}}</option>
                @endforeach
            </select>
          </div>

        </div>

  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="name" >
  </div>
  <div class="form-group">
    <label for="initial_price">Initial Price</label>
    <input type="text" class="form-control" id="initial_price" name="initial_price">
  </div>
  <div class="form-group">
    <label for="sale_price">Sale price</label>
    <input type="text" class="form-control" id="sale_price" name="sale_price">
  </div>
  <div class="form-group">
    <label for="quantity">Quantity</label>
    <input type="text" class="form-control" id="quantity" name="quantity">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>

    </div>
@endsection

resources/views/item/edit.blade.php
@extends('layouts.app')

@section('content')
    {{-- Header Background--}}
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-7">
    </div>
    <div class="card shadow mb-4 ml-5 mr-5 mt--7">
        <div class="card-header">
            <h2>Create Items</h2>
        </div>
        <form method="POST"  action="{{route('item.update', $item->id)}}">
          <div class="container">
        	@csrf
          @method('PUT')
   <div class="form-group row">
          <div class="col-sm-12">

            <label for="category_id" class="col-form-label d-inline-block">Category</label>
            <select class="form-control" name="category_id">

              @foreach ($category as $row)
                <option value="{{$row->id}}">{{$row->name}}</option>
                @endforeach
            </select>
          </div>

        </div>
  <div class="form-group" >
    <label for="item_code">Item Code</label>
    <input type="text" class="form-control" id="item_code" name="item_code" value="{{$item->item_code}}"  >
  </div>
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="name" value="{{$item->name}}" >
  </div>

  <div class="form-group">
    <label for="sale_price">Sale price</label>
    <input type="text" class="form-control" id="sale_price" name="sale_price" value="{{$item->sale_price}}" >
  </div>
  <div class="form-group">
    <label for="quantity">Quantity</label>
    <input type="text" class="form-control" id="quantity" name="quantity" value="{{$item->quantity}}" >
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>

    </div>
@endsection

resources/views/item/index.blade.php
@extends('layouts.app')

@section('content')
    {{-- Header Background--}}
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-7">
    </div>
    <div class="card shadow mb-4 ml-5 mr-5 mt--7">
        <div class="card-header">
            <h2 class="d-inline-block">Item Listings</h2>
            <a href="{{route('item.create')}}" class="btn btn-success float-right"><i class="fas fa-plus"></i> Add New </a>
        </div>

        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Item Code</th>
                        <th>Category</th>
                        <th>Sale Price</th>
                        <th>Quantity</th>
                        <th>Function</th>
                    </tr>
                </thead>

                <tbody>
                    @php
                        $i = 1;
                    @endphp

                @foreach($items as $item)
                    <tr>
                        <td>{{$i++}}</td>
                        <td>{{$item->name}}</td>
                        <td>{{$item->item_code}}</td>
                        <td>{{$item->category->name}}</td>
                        <td>{{$item->sale_price}}</td>
                        <td>{{$item->quantity}}</td>
                        <td>
                            <a href="{{route('item.edit', $item->id)}}" class="btn btn-warning"><i class="far fa-edit"></i>Edit</a>
                            <a href="javascript:;" data-toggle="modal" onclick="deleteData({{$item->id}})"
                               data-target="#DeleteModal" class="btn btn-xs btn-danger">
                                <i class="far fa-trash-alt"></i> Delete</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
       <div id="DeleteModal" class="modal fade" role="dialog">
        <div class="modal-dialog ">
            <!-- Modal content-->
            <form action="" id="deleteForm" method="post">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2 class="modal-title">Delete Comfirmation</h2>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @csrf
                        @method('DELETE')
                        <p class="text-center">Are You Sure Want To Delete ?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-danger" data-dismiss="modal" onclick="formSubmit()">Delete</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    {{-- Modal End --}}

    {{-- JS - Delete Modal --}}
    <script type="text/javascript">
        function deleteData(id)
        {
            var id = id;
            var url = '{{ route("item.destroy", ":id") }}';
            url = url.replace(':id', id);
            $("#deleteForm").attr('action', url);
        }

        function formSubmit()
        {
            $("#deleteForm").submit();
        }
    </script>
    @endsection