routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('frontend.index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

//	Custom routes
	Route::resource('sales_people', 'SalePersonController');


	Route::resource('managers', 'ManagerController');
	Route::resource('pos', 'PosController');

	Route::post('possearch', 'PosController@search')->name('Search');

	Route::resource('townships', 'TownshipController');
    Route::resource('categories', 'CategoryController');
    Route::resource('item', 'ItemController');
    Route::resource('shop','ShopController');

    Route::post('sale', 'SaleController@store')->name('sale');
});


Route::middleware(['role:Sales'])->group(function () {

});

Route::middleware(['role:Manager'])->group(function () {

});

app/Township.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Township extends Model
{
    use SoftDeletes;

    protected $fillable = ['name'];

    protected $dates = ['deleted_at'];

    public function shops()
    {
        return $this->hasMany('App\Shop');
    }
}

app/Http/Controllers/TownshipController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Township;

class TownshipController extends Controller
{
    public function index()
    {
        $township = Township::all();
        return view ('townships.index', compact('township'));
    }

    public function create()
    {
        return view('townships.create');
    }

    public function store(Request $request)
    {
        //dd($request);
        $request->validate([
            "name" => "required",
        ]);
        $township = New Township;
        $township->name = request('name');
        $township -> save();

        return redirect()->route('townships.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $township = Township::find($id);
        return view('townships.edit', compact('township'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            "name" => 'required | min:5 | max: 100'
        ]);

        $township = Township::find($id);

        $township->name = request('name');

        $township -> save();

        return redirect()->route('townships.index');
    }

    public function destroy($id)
    {
        $township = Township::find($id);
        $township -> delete();

        return redirect()->route('townships.index');
    }
}

resources/views/townships/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-7">
    </div>
    <div class="card shadow mb-4 ml-5 mr-5 mt--7">
        <div class="card-header">
            <h2>Create New Township</h2>
        </div>

        <div class="card-body">
            <form action="{{route('townships.store')}}" method="POST">
                @csrf
                <div class="form-group row">
                    <div class="col-sm-5">
                        <label for="name" class=""> Name </label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="">
                    </div>
                </div>

                <button type="submit" class="btn btn-primary ">save</button>
            </form>
        </div>
    </div>

@endsection

resources/views/townships/edit.blade.php
@extends('layouts.app')

@section('content')
    {{-- Header Background--}}
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-7">
    </div>
    <div class="card shadow mb-4 ml-5 mr-5 mt--7">
        <div class="card-header">
            <h2>Edit Category</h2>
        </div>

        <div class="card-body">
            <form method="post" action="{{route('townships.update', $township->id)}}">
                @csrf
                @method('PUT')

                <div class="form-group row" >
                    <label for="name" class="col-sm-1 col-form-label">Name :</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="name" id="name" aria-describedby="name" value="{{$township->name}}">
                        @error('name')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-primary ">Update</button>
                </div>
        </div>



        </form>
    </div>
    </div>

@endsection

resources/views/townships/index.blade.php
@extends('layouts.app')

@section('content')
    {{-- Header Background--}}
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-7">
    </div>
    <div class="card shadow mb-4 ml-5 mr-5 mt--7">
        <div class="card-header">
            <h2 class="d-inline-block">Township Listings</h2>
            <a href="{{route('townships.create')}}" class="btn btn-success float-right"><i class="fas fa-plus"></i> Add New </a>
        </div>

        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
                </thead>

                <tbody>
                @php
                    $i = 1;
                @endphp

                @foreach($township as $township)
                    <tr>
                        <td>{{$i++}}</td>
                        <td>{{$township->name}}</td>
                        <td>
                            <a href="{{route('townships.edit', $township->id)}}" class="btn btn-warning"><i class="far fa-edit"></i> Edit</a>
                            <a href="javascript:;" data-toggle="modal" onclick="deleteData({{$township->id}})"
                               data-target="#DeleteModal" class="btn btn-xs btn-danger">
                                <i class="far fa-trash-alt"></i> Delete</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>


    {{-- Modal - Delete Confirmation --}}

    <div id="DeleteModal" class="modal fade" role="dialog">
        <div class="modal-dialog ">
            <!-- Modal content-->
            <form action="" id="deleteForm" method="post">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2 class="modal-title">Delete Comfirmation</h2>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @csrf
                        @method('DELETE')
                        <p class="text-center">Are You Sure Want To Delete ?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-danger" data-dismiss="modal" onclick="formSubmit()">Delete</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    {{-- Modal End --}}

    {{-- JS - Delete Modal --}}
    <script type="text/javascript">
        function deleteData(id)
        {
            var id = id;
            var url = '{{ route("townships.destroy", ":id") }}';
            url = url.replace(':id', id);
            $("#deleteForm").attr('action', url);
        }

        function formSubmit()
        {
            $("#deleteForm").submit();
        }
    </script>
    {{-- JS - Delete Modal End --}}
@endsection