routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('frontend.index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

//	Custom routes
	Route::resource('sales_people', 'SalePersonController');


	Route::resource('managers', 'ManagerController');
	Route::resource('pos', 'PosController');

	Route::post('possearch', 'PosController@search')->name('Search');

	Route::resource('townships', 'TownshipController');
    Route::resource('categories', 'CategoryController');
    Route::resource('item', 'ItemController');
    Route::resource('shop','ShopController');

    Route::post('sale', 'SaleController@store')->name('sale');
});


Route::middleware(['role:Sales'])->group(function () {

});

Route::middleware(['role:Manager'])->group(function () {

});

app/Manager.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Manager extends Model
{
    use SoftDeletes;



    protected $dates = ['deleted_at'];

    protected $fillable = ['phone', 'address'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

     public function shop()
    {
        return $this->belongsTo('App\Shop');

    }
}

app/Http/Controllers/ManagerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Manager;
use App\User;
use App\Shop;
use Auth;
use Illuminate\Support\Facades\Hash;

class ManagerController extends Controller
{

    public function __construct()
    {
        $this->middleware('role:Admin');
    }


    public function index()
    {
        $managers = Manager::all();
        //dd($managers);
        return view('managers.index', compact('managers'));
    }

    public function create()
    {
        $manager = Manager::all();
         $shops = Shop::all();
        return view('managers.create', compact('manager','shops'));
    }

    public function store(Request $request)
    {
        $request->validate([
            "name" => "required",
            "email" => "required | unique:users",
            "phone" => "required",
            "address" => "required"
        ]);

        $user = New User;

        $user -> name = request('name');
        $user -> email = request('email');
        $user -> password = Hash::make('1234567890');
        $user -> save();
        $user->assignRole('Manager');

        $manager = new Manager();

        $manager -> user_id = $user->id;
        $manager -> shop_id = request('shop_id');
         // Fixed shop_id for now !
        $manager -> phone = request('phone');
        $manager -> address = request('address');

        $manager -> save();

        return redirect()->route('managers.index');
    }

    public function show($id)
    {
        $user = User::find($id);
        return view('managers.show', compact('user'));
    }

    public function edit($id)
    {
        $user = User::find($id);
        return view('managers.edit', compact('user'));
    }

    public function update(Request $request, $id)
    {
        $user = User::where('id', $id)->update([
            'name' => $request->name,
            'email' => $request->email
        ]);

        $managers = Manager::where('user_id', $id)->update([
            'phone' => $request->phone,
            'address' => $request->address
        ]);

        return redirect()->route('managers.index');
    }

    public function destroy($id)
    {

        Manager::where('user_id',$id)->delete();
        User::find($id)->delete();

        return redirect()->route('managers.index');
    }
}

resources/views/managers/create.blade.php
@extends('layouts.app')

@section('content')
    {{-- Header Background--}}
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-7">
    </div>
    <div class="card shadow mb-4 ml-5 mr-5 mt--7">
        <div class="card-header">
            <h2>Create New Manager</h2>
        </div>

        <div class="card-body">
            <form method="post" action="{{route('managers.store')}}">
                @csrf

                <div class="form-group row">
                    <label for="name" class="col-sm-1 col-form-label">Name :</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="name" id="name" aria-describedby="name">
                        @error('name')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>


                    <label for="email" class="col-sm-1 col-form-label">Email :</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="email" id="email" aria-describedby="email">
                        @error('email')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-5">

                        <label for="shop_id" class="col-form-label d-inline-block">Shop</label>
                        <select class="form-control" name="shop_id">

                            @foreach ($shops as $row)

                            <option value="{{$row->id}}">{{$row->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="phone" class="col-sm-1 col-form-label">Phone :</label>
                    <div class="col-sm-5">
                        <input type="phone" class="form-control" name="phone" id="phone" aria-describedby="phone">
                        @error('phone')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <label for="email" class="col-sm-1 col-form-label">Address:</label>
                    <div class="col-sm-5">
                        <textarea class="form-control" name="address" id="address" rows="2"></textarea>
                        @error('email')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>

                <button type="submit" class="btn btn-primary mb-2">Save</button>

            </form>
        </div>
    </div>

@endsection

resources/views/managers/edit.blade.php
@extends('layouts.app')

@section('content')
    {{-- Header Background--}}
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-7">
    </div>
    <div class="card shadow mb-4 ml-5 mr-5 mt--7">
        <div class="card-header">
            <h2>Edit Manager</h2>
        </div>

        <div class="card-body">
            <form method="post" action="{{route('managers.update', $user->id)}}">
                @csrf
                @method('PUT')

                <div class="form-group row">
                    <label for="name" class="col-sm-1 col-form-label">Name :</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="name" id="name" aria-describedby="name" value="{{$user->name}}">
                        @error('name')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <label for="email" class="col-sm-1 col-form-label">Email :</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="email" id="email" aria-describedby="email" value="{{$user->email}}">
                        @error('email')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="phone" class="col-sm-1 col-form-label">Phone :</label>
                    <div class="col-sm-5">
                        <input type="phone" class="form-control" name="phone" id="phone" aria-describedby="phone" value="{{$user->manager->phone}}">
                        @error('phone')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <label for="email" class="col-sm-1 col-form-label">Address:</label>
                    <div class="col-sm-5">
                        <textarea class="form-control" name="address" id="address" rows="2">{{$user->manager->address}}</textarea>
                        @error('email')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>


                <button type="submit" class="btn btn-primary mb-2">Update</button>

            </form>
        </div>
    </div>

@endsection

resources/views/managers/index.blade.php
@extends('layouts.app')

@section('content')
    {{-- Header Background--}}
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-7">
    </div>
    <div class="card shadow mb-4 ml-5 mr-5 mt--7">
        <div class="card-header">
            <h2 class="d-inline-block">Manager Listings</h2>
            <a href="{{route('managers.create')}}" class="btn btn-success float-right"><i class="fas fa-plus"></i> Add New </a>
        </div>

        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Name</th>
                    <th>Shop</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Actions</th>
                </tr>
                </thead>

                <tbody>
                @php
                    $i = 1;
                @endphp

                @foreach($managers as $manager)
                    <tr>
                        <td>{{$i++}}</td>
                        <td>{{$manager->user->name}}</td>
                        <td>{{$manager->shop->name}}</td>
                        <td>{{$manager->user->email}}</td>
                        <td>{{$manager->phone}}</td>
                        <td>
                            <a href="{{route('managers.show', $manager->user->id)}}" class="btn btn-primary"><i class="far fa-edit"></i> Detail</a>
                            <a href="{{route('managers.edit', $manager->user->id)}}" class="btn btn-warning"><i class="far fa-edit"></i> Edit</a>
                            <a href="javascript:;" data-toggle="modal" onclick="deleteData({{$manager->user->manager->id}})"
                               data-target="#DeleteModal" class="btn btn-xs btn-danger">
                                <i class="far fa-trash-alt"></i> Delete</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>


    {{-- Modal - Delete Confirmation --}}

    <div id="DeleteModal" class="modal fade" role="dialog">
        <div class="modal-dialog ">
            <!-- Modal content-->
            <form action="" id="deleteForm" method="post">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2 class="modal-title">Delete Comfirmation</h2>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @csrf
                        @method('DELETE')
                        <p class="text-center">Are You Sure Want To Delete ?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-danger" data-dismiss="modal" onclick="formSubmit()">Delete</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    {{-- Modal End --}}

    {{-- JS - Delete Modal --}}
    <script type="text/javascript">
        function deleteData(id)
        {
            var id = id;
            var url = '{{ route("managers.destroy", ":id") }}';
            url = url.replace(':id', id);
            $("#deleteForm").attr('action', url);
        }

        function formSubmit()
        {
            $("#deleteForm").submit();
        }
    </script>
    {{-- JS - Delete Modal End --}}
@endsection

resources/views/managers/show.blade.php
@extends('layouts.app')

@section('content')
    {{-- Header Background--}}
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-7">
    </div>
    <div class="card shadow mb-4 ml-5 mr-5 mt--7">
        <div class="card-header">
            <h2 class="d-inline-block">Manager Information</h2>
        </div>

        <div class="card-body">
            <form>
                @csrf
                @method('PUT')

                <div class="form-group row">
                    <label for="name" class="col-sm-1 col-form-label">Name :</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="name" id="name" aria-describedby="name" value="{{$user->name}}" disabled>
                    </div>

                    <label for="email" class="col-sm-1 col-form-label">Email :</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="email" id="email" aria-describedby="email" value="{{$user->email}}" disabled>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="phone" class="col-sm-1 col-form-label">Phone :</label>
                    <div class="col-sm-5">
                        <input type="phone" class="form-control" name="phone" id="phone" aria-describedby="phone" value="{{$user->manager->phone}}" disabled>
                    </div>

                    <label for="email" class="col-sm-1 col-form-label">Address:</label>
                    <div class="col-sm-5">
                        <textarea class="form-control" name="address" id="address" rows="2" disabled>{{$user->manager->address}}</textarea>
                    </div>
                </div>

                <a href="{{route('sales_people.index')}}" class="btn btn-primary">Back</a>

            </form>
        </div>
    </div>

@endsection